name: "HCL AppScan SAST"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: bao-lu/test-appscan-sast-action@v1.1.5
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: d0d2e72c-d8d2-4020-97b8-a48108af602e
          service_url: ${{secrets.SERVICE_URL}}
